CREATE TABLE users (
  id BINARY(16) NOT NULL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  state LONGTEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);